config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stores do
    member do
      get 'show_memberships'
    end
  end
  put '/search_client', to: 'clients#search_client'
  resources :clients
  resources :transactions

  root 'stores#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :memberships
	has_many :stores, through: :memberships
	has_many :transactions

	def addpoints! points_awarded
		if self.points.nil?
			self.points = 0
		end
		self.points = self.points + points_awarded
		self.save!
	end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :client
	belongs_to :store

	def addpoints! points_awarded
		if self.points.nil?
			self.points = 0
		end
		self.points = self.points + points_awarded
		self.save!
	end
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :memberships
	has_many :clients, through: :memberships
	has_many :transactions
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	belongs_to :client
	belongs_to :store

	monetize :total_cents
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success, :error, :notice
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all.paginate(page: params[:page], per_page: 10).order('points DESC')
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
    @client.cedula = params[:document]
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to new_transaction_path(client_document: @client.cedula, store_id: params[:store_id]), success: 'Client was successfully created. You can proceed with the transaction.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_client
    client = Client.find_by(cedula: params[:document])
    if client.nil?
      redirect_to new_client_path(document: params[:document], store_id: params[:store_id]), notice: 'The client is not registered, you need to register him first'
    else
      redirect_to new_transaction_path(client_document: client.cedula, store_id: params[:store_id]), notice: 'You can proceed with the transaction'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:full_name, :gender, :cedula, :phone, :birthday, :age, :address)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy, :show_memberships]
  before_filter :authenticate_user!
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_memberships
    @memberships = @store.memberships.paginate(page: params[:page], per_page: 10).order('points DESC')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :type_of_store, :address, :phone, :description, :pointsfirst, :pointssecond, :pointsthird, :rewardfirst, :rewardsecond, :rewardthird)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	before_action :set_transaction, only: [:show]
	def new
		@transaction = Transaction.new
		@client = Client.find_by(cedula: params[:client_document])
	end
	def create
	    @transaction = Transaction.new(transaction_params)
	    @transaction.client = Client.find_by(cedula: params[:client_document])
	    @transaction.store = Store.find(params[:store_id])
	    membership = ((Membership.find_by(store_id: @transaction.store.id, client_id: @transaction.client.id)).nil?) ? Membership.new : Membership.find_by(store_id: @transaction.store.id, client_id: @transaction.client.id)
	    
	    respond_to do |format|
	      if @transaction.save
	      	@transaction.client.addpoints!(@transaction.points_awarded)
	      	if membership.persisted?
	      		membership.addpoints!(@transaction.points_awarded)
	    	else
	    		membership.client = @transaction.client
	    		membership.store = @transaction.store
	    		membership.save!
	    		membership.addpoints!(@transaction.points_awarded)
	    	end
	        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
	        format.json { render :show, status: :created, location: @transaction }
	      else
	        format.html { render :new }
	        format.json { render json: @transaction.errors, status: :unprocessable_entity }
	      end
	    end		
	end

	def show

	end
	private
	# Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:description, :total, :points_awarded)
    end
    def set_transaction
    	@transaction = Transaction.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :cedula %><br>
    <%= f.text_field :cedula %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <%= hidden_field_tag 'store_id', params[:store_id] %>
  <div class="actions">
    <%= f.submit 'Submit', class: "button small-6 columns expand" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Loyal customers</h1>
<div class="row">
  <div class="small-12 columns small-centered">
    <table>
      <thead>
        <tr>
          <th>Pos.</th>
          <th>Points</th>
          <th>ID</th>
          <th>Full name</th>
        </tr>
      </thead>

      <tbody>
        <% i = 1 %> 
        <% @clients.each do |client| %>
          <tr>
            <td>#<%= i %></td>
            <td><span class="label round"><%= client.points %></span></td>
            <td><%= client.cedula %></td>
            <td><%= link_to client.full_name, client %></td>
          </tr>
          <% i = i + 1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<div id="paginator">
  <%= will_paginate @clients, renderer: FoundationPagination::Rails, :previous_label => '<', :next_label => '>' %>
</div>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<h1>Viewing client</h1>

<p>
  <strong>Full name:</strong>
  <%= @client.full_name %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @client.cedula %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @client.gender %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @client.birthday %>
</p>

<p>
  <strong>Age:</strong>
  <%= @client.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Destroy', @client, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
	<div data-alert class="flash alert-box text-center <%= type %>">
		<%= message %>
		<a href="#" class="close">&times;</a>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/flash' %>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Leal program", root_path %></h1>
        </li>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <% if user_signed_in? %>
          <!-- Right Nav Section -->
          <ul class="right">
            <li><%= link_to %Q|Log out|, destroy_user_session_path, :method => 'delete', class: "" %></li>
          </ul>
          <!-- Left Nav Section -->
          <ul class="left">
            <li><%= link_to "Stores", root_path %></li>
            <li><%= link_to "Top loyal customers", clients_path %></li>
          </ul>
        <% end %>
      </section>
    </nav>
    
    <div class="row collapse principal">
      <div class="small-12 small-centered medium-6 medium-centered large-6 large-centered columns">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type_of_store %><br>
    <%= f.text_field :type_of_store %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <fieldset>
    <legend>Rewards</legend>
    <div class="field">
      <%= f.label :pointsfirst, "Points first" %><br>
      <%= f.text_field :pointsfirst %>
    </div>
    <div class="field">
      <%= f.label :rewardfirst, "first reward" %><br>
      <%= f.text_field :rewardfirst %>
    </div>
    <div class="field">
      <%= f.label :pointssecond, "Points second" %><br>
      <%= f.text_field :pointssecond %>
    </div>
    <div class="field">
      <%= f.label :rewardsecond, "second reward" %><br>
      <%= f.text_field :rewardsecond %>
    </div>
    <div class="field">
      <%= f.label :pointsthird, "Points third" %><br>
      <%= f.text_field :pointsthird %>
    </div>
    <div class="field">
      <%= f.label :rewardthird, "Third reward" %><br>
      <%= f.text_field :rewardthird %>
    </div>
  </fieldset>
  <div class="actions">
    <%= f.submit 'Submit', class: "button small-6 columns expand" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing Stores</h1>

<div class="row">
  <div class="small-6 columns small-centered">
      <%= link_to 'Add Store', new_store_path, class: "button radius expand" %>
  </div>
</div>

<div class="row store-grid">
  <div class="small-12 columns">
    <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-3">
      <% @stores.each do |store| %>
        <li class="th">
          <h5 class="truncate"><%= link_to store.name, store %></h5>
          <div class="row">
            <div class="small-6 columns">
                <%= link_to 'Show', store, class: "button radius tiny expand" %>
            </div>
            <div class="small-6 columns">
                <%= link_to 'Edit', edit_store_path(store), class: "button radius tiny expand secondary" %>    
            </div>
          </div>
        </li>
      <% end %>  
    </ul>
  </div>
</div>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<h1>Viewing <%= @store.name %></h1>
<div class="row">
  <div class="small-6 columns">
    <p>
      <strong>Type:</strong>
      <%= @store.type_of_store %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @store.address %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @store.phone %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @store.description %>
    </p>
    <fieldset>
      <legend>Rewards</legend>
      <p>
        <strong>First reward:</strong>
        <%= @store.rewardfirst %> for <%= @store.pointsfirst %> Points
      </p>
      <p>
        <strong>Second reward:</strong>
        <%= @store.rewardsecond %> for <%= @store.pointssecond %> Points
      </p>
      <p>
        <strong>Third reward:</strong>
        <%= @store.rewardthird %> for <%= @store.pointsthird %> Points
      </p>
    </fieldset>
  </div>
  <div class="small-6 columns">
    <%= link_to "Create transaction", @store, class: "button radius small-12 columns", data: { "reveal-id" => "transaction-modal" } %>
    <%= link_to "View loyal customers of this store", show_memberships_store_path(@store), class: "button radius small-12 columns secondary" %>
  </div>
</div>



<%= link_to 'Edit', edit_store_path(@store) %> | <%= link_to 'Destroy', @store, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', stores_path %>

<div id="transaction-modal" class="reveal-modal small" data-reveal>
  <a class="close-reveal-modal">&#215;</a>
  <%= form_tag search_client_path(store_id: @store.id), method: :put do |f| %>
    <%= label_tag :document, "Enter Client's document" %>
    <%= text_field_tag :document %>
    <%= submit_tag "Next", class: "button radius medium expand submit" %>
  <% end %>
</div>

app/views/stores/show_memberships.html.erb
<h1>Loyal Customers of <%= @store.name %></h1>
<div class="row">
  <div class="small-12 columns small-centered">
    <table>
      <thead>
        <tr>
          <th>Pos.</th>
          <th>Points</th>
          <th>ID</th>
          <th>Full name</th>
        </tr>
      </thead>

      <tbody>
        <% i = 1 %> 
        <% @memberships.each do |membership| %>
          <tr>
            <td>#<%= i %></td>
            <td><span class="label round"><%= membership.client.points %><span></td>
            <td><%= membership.client.cedula %></td>
            <td><%= link_to membership.client.full_name, membership.client %></td>
          </tr>
          <% i = i + 1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<div id="paginator">
  <%= will_paginate @memberships, renderer: FoundationPagination::Rails, :previous_label => '<', :next_label => '>' %>
</div>

app/views/transactions/new.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :points_awarded %><br>
    <%= f.text_field :points_awarded %>
  </div>
  <%= hidden_field_tag 'store_id', params[:store_id] %>
  <%= hidden_field_tag 'client_document', params[:client_document] %>
  <div class="actions">
    <%= f.submit 'Submit', class: "button small-6 columns expand" %>
  </div>
<% end %>

app/views/transactions/show.html.erb
<h1>Transaction #<%= @transaction.id %> <%= @transaction.created_at.strftime("Created at %d/%m/%Y") %></h1>
<div class="row">
  <div class="small-6 columns">
    <p>
      <strong>Description:</strong>
      <%= @transaction.description %>
    </p>
    <p>
      <strong>total:</strong>
      <%= humanized_money_with_symbol @transaction.total %>
    </p>
    <p>
      <strong>Points awarded:</strong>
      <span class="label round"><%= @transaction.points_awarded %></span>
    </p>
  </div>
  <div class="small-6 columns">
    <strong>Billed to:</strong><br>
    <%= @transaction.client.full_name %><br>
    <strong>Billed for:</strong><br>
    <%= @transaction.store.name %>
  </div>
</div>